# Generated by Django 2.1.5 on 2019-05-29 14:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0008_auto_20190117_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='realtime_strains',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
