# Generated by Django 2.1.5 on 2019-05-30 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0009_sequencingrun_realtime_strains'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='sample_plate',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
