# Generated by Django 2.1.5 on 2019-08-23 19:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0010_sequencingrun_sample_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='emails_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
