# Generated by Django 2.1.5 on 2019-08-23 19:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0011_auto_20190823_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
    ]
