# Generated by Django 2.1.5 on 2019-08-23 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0012_auto_20190823_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='realtime_strains',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='sample_plate',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
