# Generated by Django 2.1.5 on 2019-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0013_auto_20190823_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='progress',
            field=models.CharField(default='Unprocessed', max_length=64),
        ),
    ]
