# Generated by Django 2.1.5 on 2019-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0014_sequencingrun_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='run_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
