# Generated by Django 2.1.5 on 2019-09-12 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0018_auto_20190912_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='seqids_to_upload',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='uploaded_seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
    ]
