# Generated by Django 2.1.5 on 2019-09-13 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0019_auto_20190912_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencingrun',
            old_name='seqids_to_upload',
            new_name='forward_reads_to_upload',
        ),
        migrations.RenameField(
            model_name='sequencingrun',
            old_name='uploaded_seqids',
            new_name='uploaded_forward_reads',
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='reverse_reads_to_upload',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='uploaded_reverse_reads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
    ]
