# Generated by Django 2.1.11 on 2019-12-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0021_sequencingrun_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='exit_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
