# Generated by Django 2.1.11 on 2019-12-31 13:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0022_sequencingrun_exit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
