# Generated by Django 2.1.11 on 2020-01-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0023_auto_20191231_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='progress',
            field=models.CharField(default='Unprocessed', max_length=128),
        ),
    ]
