# Generated by Django 2.1.11 on 2022-06-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0026_auto_20220601_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrun',
            name='container',
            field=models.CharField(default='sequencing-runs', max_length=64),
        ),
    ]
