# Generated by Django 2.1.11 on 2022-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0028_auto_20220601_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrun',
            name='container',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
