# Generated by Django 2.1.11 on 2022-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0030_auto_20220601_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchrun',
            name='container',
        ),
        migrations.RemoveField(
            model_name='researchrun',
            name='sequencing_run',
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='container',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
