# Generated by Django 2.1.11 on 2022-06-28 15:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0031_auto_20220601_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_results', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('sequencing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_metadata', to='cowbat.SequencingRun')),
            ],
        ),
    ]
