# Generated by Django 2.1.11 on 2022-08-02 19:42

from django.db import migrations, models
import olc_webportalv2.cowbat.models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0032_summarymetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_file',
            field=models.FileField(storage=olc_webportalv2.cowbat.models.OverwriteStorage(), upload_to=olc_webportalv2.cowbat.models.get_run_name),
        ),
    ]
