# Generated by Django 2.1.11 on 2022-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0033_auto_20220802_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='basic_assembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='preprocess',
            field=models.BooleanField(default=False),
        ),
    ]
