# Generated by Django 2.1.11 on 2024-03-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0036_auto_20240117_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarymetadata',
            name='sequencing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarymetadata', to='cowbat.SequencingRun'),
        ),
    ]
