# Generated by Django 2.1.11 on 2024-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0037_auto_20240305_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='nextseq',
            field=models.BooleanField(default=False),
        ),
    ]
