# Generated by Django 2.1.11 on 2024-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0038_sequencingrun_nextseq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='nextseq',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
