# Generated by Django 2.1.11 on 2024-06-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0039_auto_20240312_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='batch_submit_errors',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='batch_submit_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='pool_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
