# Generated by Django 2.1.11 on 2024-06-07 18:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowbat', '0040_auto_20240606_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='percent_complete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=5),
        ),
    ]
