# Generated by Django 2.1.11 on 2026-01-29 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cowbat', '0041_sequencingrun_percent_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencing_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
