version: '2'

services:
  web: &web
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./:/data/web
      - ./sequences:/sequences
      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container
    environment:
      - POSTGRES_USER=myproject_web
      - USE_DOCKER=yes
      - DOCKER_SOCKET=/var/run/docker.sock
      - DOCKER_GROUP=dockerhost
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SECRET_KEY=asdfjkl
      - AZURE_ACCOUNT_NAME=$AZURE_ACCOUNT_NAME
      - AZURE_ACCOUNT_KEY=$AZURE_ACCOUNT_KEY
      - BATCH_ACCOUNT_NAME=$BATCH_ACCOUNT_NAME
      - BATCH_ACCOUNT_URL=$BATCH_ACCOUNT_URL
      - BATCH_ACCOUNT_KEY=$BATCH_ACCOUNT_KEY
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - VM_IMAGE=$VM_IMAGE
      - VM_CLIENT_ID=$VM_CLIENT_ID
      - VM_SECRET=$VM_SECRET
      - VM_TENANT=$VM_TENANT
      - DB_NAME=project_db
      - DB_USER=project_user
      - DB_PASS=fakepassword
      - DB_SERVICE=postgres
      - DB_PORT=5432
    ports:
      - "8000"
    command: /bin/bash -c "gunicorn config.wsgi:application -w 4 -b :8000 -t 3600"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:9.6
    environment:
      - DB_NAME=project_db
      - DB_USER=project_user
      - DB_PASS=fakepassword
      - DB_SERVICE=postgres
      - DB_PORT=5432
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
      - ./postgres-data-test:/var/lib/postgresql/data
    expose:
      - "5432"

  redis:
    image: redis:3.0

  celeryworker:
    # https://github.com/docker/compose/issues/3220
    <<: *web
    depends_on:
      - redis
      - postgres
    command: ./worker_launcher.sh
      

  celerybeat:
    # https://github.com/docker/compose/issues/3220
    <<: *web
    depends_on:
      - redis
      - postgres
    ports: []
#    command: /start-celerybeat.sh

  flower:
     <<: *web
     depends_on:
       - celeryworker
       - celerybeat
     command: ["flower", "--basic_auth=$FLOWER_USER:$FLOWER_PASSWORD","--broker=redis://redis:6379/0", "--port=8888"]
     ports:
      - 8888:8888


