services:
  web: &web
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - redis:redis
      - batch:batch
    env_file: env
    volumes:
      - ./:/data/web
      - ../AzureBatch:/data/AzureBatch
      - ./sequences:/sequences
      - /var/run/docker.sock:/var/run/docker.sock # send docker commands from the django docker container
    environment:
      - POSTGRES_USER=myproject_web
      - USE_DOCKER=yes
      - DOCKER_SOCKET=/var/run/docker.sock
      - DOCKER_GROUP=dockerhost
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8000"
    command: /bin/bash -c "gunicorn config.wsgi:application --reload -w 4 -b :8000 -t 3600"

  batch:
    restart: always
    build:
      context: ./batch
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: env
    volumes:
      - ./batch:/app
    command: ["/app/start.sh"]

  redmine:
    restart: always
    build:
      context: ./redmine
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - mariadb
    env_file:
      - env
    # ENTRA_ID_CLIENT_ID, ENTRA_ID_CLIENT_SECRET and ENTRA_ID_TENANT_ID are loaded from env
    environment:
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=${MYSQL_PASSWORD}
      - REDMINE_NO_DB_MIGRATE=1
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/log:/usr/src/redmine/log
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml:rw
      - ./redmine/config/database.yml:/usr/src/redmine/config/database.yml:rw
      - ./redmine/config/secrets.yml:/usr/src/redmine/config/secrets.yml:rw
      - ./redmine/config/initializers/smtp_retry.rb:/usr/src/redmine/config/initializers/smtp_retry.rb:rw
      - ./redmine/issue_export:/usr/src/redmine/issue_export:rw
      - ./redmine/attachments:/usr/src/redmine/attachments:rw
    ports:
      - "3000:3000"
    command: ["bundle", "exec", "bash", "/usr/src/redmine/boot-redmine.sh"]

  mariadb:
    restart: always
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
    volumes:
      - redmine-db:/var/lib/mysql

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web
    volumes:
      # - ./nginx/certs:/etc/nginx/certs:ro
      - /etc/foodport/tls:/etc/nginx/certs:ro
    links:
      - web:web
      - redmine:redmine

  redis:
    restart: always
    image: redis:3.0

  celeryworker:
    restart: always
    <<: *web
    depends_on:
      - redis
    command: ./worker_launcher.sh

  celerybeat:
    restart: always
    <<: *web
    depends_on:
      - redis
    ports: []
    command: celery -A olc_webportalv2.taskapp beat -l info

  flower:
    restart: always
    <<: *web
    depends_on:
      - celeryworker
      - celerybeat
    command: [
      "flower",
      "--basic_auth=$FLOWER_USER:$FLOWER_PASSWORD",
      "--broker=redis://redis:6379/0",
      "--port=8888"
    ]
    ports:
      - "8888:8888"

volumes:
  redmine-db:
