# Generated by Django 2.1.5 on 2019-04-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_labid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labid',
            old_name='labID',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='labID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.LabID'),
        ),
    ]
