# Generated by Django 2.1.5 on 2019-04-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20190409_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labid',
            old_name='ID',
            new_name='labid',
        ),
        migrations.RenameField(
            model_name='sequencedata',
            old_name='labID',
            new_name='labid',
        ),
    ]
