# Generated by Django 2.1.5 on 2019-04-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20190409_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencedata',
            name='labid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.LabID'),
        ),
    ]
