# Generated by Django 2.1.5 on 2019-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20190410_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencedata',
            name='mlst',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='rmlst',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='serotype',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='species',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
