# Generated by Django 2.1.5 on 2019-07-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_genus_mlst_rmlst_serotype_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLNID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olnid', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='olnid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.OLNID'),
        ),
    ]
