# Generated by Django 2.1.5 on 2019-08-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20190820_1823'),
        ('metadata', '0010_auto_20190723_1853'),
    ]

    operations = [
    ]
