# Generated by Django 2.1.5 on 2019-08-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_merge_20190821_1833'),
        ('metadata', '0010_auto_20190726_1511'),
    ]

    operations = [
    ]
