# Generated by Django 2.1.5 on 2019-08-23 19:33

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_merge_20190822_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatarequest',
            name='criteria',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='metadatarequest',
            name='seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
    ]
