# Generated by Django 2.1.5 on 2019-08-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_auto_20190823_1933'),
        ('metadata', '0012_merge_20190823_1237'),
    ]

    operations = [
    ]
