# Generated by Django 2.1.5 on 2019-10-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_merge_20190826_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='genus',
            field=models.CharField(max_length=48, verbose_name='genus'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='quality',
            field=models.CharField(choices=[('Fail', 'Fail'), ('Pass', 'Pass'), ('Reference', 'Reference')], max_length=128, verbose_name='quality'),
        ),
        migrations.AlterField(
            model_name='serotype',
            name='serotype',
            field=models.CharField(max_length=48, verbose_name='serotype'),
        ),
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(max_length=48, verbose_name='species'),
        ),
    ]
