# Generated by Django 2.1.11 on 2024-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_auto_20191007_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labid',
            name='labid',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='olnid',
            name='olnid',
            field=models.CharField(max_length=48),
        ),
    ]
