# Generated by Django 2.1.11 on 2024-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_auto_20240911_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labid',
            name='labid',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
