# Generated by Django 2.1.11 on 2020-03-12 14:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('cfiaid', models.CharField(max_length=48)),
                ('rmlst', models.CharField(max_length=48)),
                ('mlst', models.CharField(max_length=24)),
                ('mlst_cc', models.CharField(max_length=24)),
                ('genus', models.CharField(max_length=48)),
                ('species', models.CharField(max_length=48)),
                ('serovar', models.CharField(max_length=512)),
                ('geneseekr', models.CharField(max_length=48)),
                ('vtyper', models.CharField(max_length=48)),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseRequestIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='GeneSeekr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('geneseekr', models.CharField(blank=True, max_length=48)),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('genus', models.CharField(blank=True, max_length=48, verbose_name='genus')),
            ],
        ),
        migrations.CreateModel(
            name='LabID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labid', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='LookupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('olnid', models.CharField(max_length=48)),
                ('labid', models.CharField(max_length=48)),
                ('biosample', models.CharField(max_length=48)),
                ('other_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MLST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('mlst', models.CharField(blank=True, max_length=12)),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
            ],
        ),
        migrations.CreateModel(
            name='MLSTCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('mlst_cc', models.CharField(blank=True, max_length=12)),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
            ],
        ),
        migrations.CreateModel(
            name='NameTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('cfiaid', models.CharField(max_length=48)),
                ('curatorflag', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='OLNID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olnid', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='RMLST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('rmlst', models.CharField(blank=True, max_length=12)),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
                ('cfiaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_database.NameTable')),
                ('geneseekr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.GeneSeekr')),
                ('genus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Genus')),
                ('mlst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.MLST')),
                ('mlst_cc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.MLSTCC')),
                ('rmlst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.RMLST')),
            ],
        ),
        migrations.CreateModel(
            name='Serovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('serovar', models.CharField(blank=True, max_length=512, verbose_name='serovar')),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('species', models.CharField(blank=True, max_length=48, verbose_name='species')),
            ],
        ),
        migrations.CreateModel(
            name='UniqueGeneSeekr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneseekr', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueGenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueMLST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlst', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueMLSTCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlst_cc', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueRMLST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmlst', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueSerovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serovar', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueVtyper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtyper', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Vtyper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('vtyper', models.CharField(blank=True, max_length=48)),
                ('version', models.CharField(blank=True, max_length=48, null=True, verbose_name='database_version')),
                ('typing_date', models.DateField(blank=True, null=True, verbose_name='typing_date')),
            ],
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='serovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Serovar'),
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Species'),
        ),
        migrations.AddField(
            model_name='sequencedata',
            name='vtyper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Vtyper'),
        ),
        migrations.AddField(
            model_name='lookuptable',
            name='cfiaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_database.NameTable'),
        ),
    ]
