# Generated by Django 2.1.11 on 2020-03-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencedata',
            name='cfiaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence_database.NameTable', verbose_name='CFIA ID'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='geneseekr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.GeneSeekr', verbose_name='GeneSeekr Profile'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Genus', verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='mlst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.MLST', verbose_name='MLST Profile'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='mlst_cc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.MLSTCC', verbose_name='MLST Clonal Complex'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='rmlst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.RMLST', verbose_name='MLST Profile'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='seqid',
            field=models.CharField(max_length=24, verbose_name='SEQID'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='serovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Serovar', verbose_name='Serovar'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Species', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='typing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Typing Date'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='version',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Database Version'),
        ),
        migrations.AlterField(
            model_name='sequencedata',
            name='vtyper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_database.Vtyper', verbose_name='Vtyper Profile'),
        ),
    ]
