# Generated by Django 2.1.11 on 2020-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_database', '0003_auto_20200318_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_fields', models.CharField(choices=[('SEQID', 'SEQ ID'), ('CFIAID', 'CFIA ID'), ('GENUS', 'Genus'), ('SPECIES', 'Species'), ('MLST', 'MLST Profile'), ('MLSTCC', 'MLST Clonal Complex'), ('RMLST', 'rMLST Profile'), ('GENESEEKR', 'GeneSeekr Profile'), ('SEROVAR', 'Serovar'), ('VTYPER', 'Vtyper Profile'), ('VERSION', 'Pipeline Version'), ('TYPING DATE', 'Typing Date')], default='GENUS', max_length=24)),
                ('query_operators', models.CharField(choices=[('AND', 'and'), ('OR', 'or'), ('BEFORE', 'before'), ('AFTER', 'after'), ('EXACTLY', 'exactly')], default='AND', max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='DatabaseFields',
        ),
        migrations.DeleteModel(
            name='Operators',
        ),
    ]
