# Generated by Django 2.1.11 on 2020-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_database', '0004_auto_20200318_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasequery',
            name='qualifiers',
            field=models.CharField(choices=[('CONTAINS', 'contains'), ('EXACT', 'exact'), ('BEFORE', 'before'), ('AFTER', 'after')], default='CONTAINS', max_length=12),
        ),
        migrations.AddField(
            model_name='databasequery',
            name='query',
            field=models.CharField(default='', max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databasequery',
            name='query_operators',
            field=models.CharField(choices=[('AND', 'and'), ('OR', 'or')], default='AND', max_length=12),
        ),
    ]
