# Generated by Django 2.1.11 on 2020-03-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_database', '0005_auto_20200318_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasequery',
            name='query_operators',
            field=models.CharField(choices=[('AND', 'and'), ('OR', 'or'), ('NOT', 'not')], default='AND', max_length=12),
        ),
    ]
