# Generated by Django 2.1.11 on 2020-03-24 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_database', '0009_auto_20200318_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaserequestids',
            name='cfiaids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
    ]
