# Generated by Django 2.1.11 on 2020-03-24 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_database', '0010_databaserequestids_cfiaids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaserequestids',
            name='cfiaids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), blank=True, default=list, size=None),
        ),
    ]
