---
production:
  rest_api_enabled: true
  login_required: true
  allow_password_change: true
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: email-smtp.ca-central-1.amazonaws.com
      port: 587
      domain: inspection.gc.ca
      authentication: :login
      enable_starttls_auto: true
      user_name: AKIA4DJHEGSUOUVSDQGV
      password: BET13W9isVZOJXbHy8B94ES22at4L5sKynPgvZxjcrI+
  default_from: CFIA Redmine <cfia.foodport.donotreply-nepasrepondre.aliport.acia@inspection.gc.ca>
  self_registration: false
  default_language: en
  default_timezone: UTC
  enabled_login_sources: []
  time_zone: UTC
