# Generated by Django 2.1.11 on 2020-01-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('path', models.FileField(upload_to='')),
                ('sequence_path', models.FileField(upload_to='')),
                ('primer_file', models.FileField(upload_to='')),
                ('mismatches', models.CharField(default=False, max_length=50)),
                ('kmer_length', models.CharField(default=False, max_length=50)),
                ('cpus', models.CharField(default=False, max_length=50)),
                ('analysistype', models.CharField(default=False, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
