# Generated by Django 2.1.11 on 2023-10-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cowsnphrazuretask',
            old_name='ampliseq',
            new_name='cowsnphr',
        ),
    ]
