# Generated by Django 2.1.11 on 2023-11-06 18:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0002_auto_20231018_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOutputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.TextField(blank=True, null=True)),
                ('amino_acid_summary_table', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('assembly_report', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('contig_summary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('nucleotide_summary_table', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('phylogenetic_tree', models.TextField(blank=True, null=True)),
                ('snv_matrix', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('snv_summary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('cowsnphr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cowsnphr', to='cowsnphr.COWSNPhRRequest')),
            ],
        ),
    ]
