# Generated by Django 2.1.11 on 2023-11-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0003_reportoutputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowsnphrrequest',
            name='execution_report_download_link',
        ),
        migrations.RemoveField(
            model_name='cowsnphrrequest',
            name='execution_timeline_download_link',
        ),
        migrations.RemoveField(
            model_name='cowsnphrrequest',
            name='execution_trace_download_link',
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='archive_download_link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
