# Generated by Django 2.1.11 on 2023-11-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0004_auto_20231106_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportoutputs',
            name='cowsnphr',
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='alignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='amino_acid_summary_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='assembly_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='contig_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='nucleotide_summary_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='phylogenetic_tree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='snv_matrix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='snv_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReportOutputs',
        ),
    ]
