# Generated by Django 2.1.11 on 2023-11-07 20:28

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0005_auto_20231107_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='amino_acid_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='assembly_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='contig_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='nucleotide_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='snv_matrix_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='snv_summary_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cowsnphrrequest',
            name='amino_acid_summary_table',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cowsnphrrequest',
            name='assembly_report',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cowsnphrrequest',
            name='contig_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cowsnphrrequest',
            name='nucleotide_summary_table',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cowsnphrrequest',
            name='snv_matrix',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cowsnphrrequest',
            name='snv_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
