# Generated by Django 2.1.11 on 2023-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0006_auto_20231107_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='amino_acid_header_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='nucleotide_header_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
