# Generated by Django 2.1.11 on 2023-11-10 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0007_auto_20231110_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowsnphrrequest',
            name='amino_acid_header_length',
        ),
        migrations.RemoveField(
            model_name='cowsnphrrequest',
            name='nucleotide_header_length',
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='amino_acid_header_padding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='nucleotide_header_padding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
