# Generated by Django 2.1.11 on 2023-11-28 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0008_auto_20231110_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
    ]
