# Generated by Django 2.1.11 on 2023-11-28 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0009_auto_20231128_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowsnphrrequest',
            name='seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, default=list, size=None),
        ),
    ]
