# Generated by Django 2.1.11 on 2023-11-28 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsnphr', '0010_auto_20231128_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsnphrrequest',
            name='seqid_errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
