# Generated by Django 2.1.11 on 2023-07-05 19:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import olc_webportalv2.ampliseq.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpliSeqRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('report_download_link', models.CharField(blank=True, max_length=256)),
                ('summary_download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('errors', models.TextField(blank=True, default='')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
                ('emails_array', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('container_name', models.CharField(blank=True, max_length=64)),
                ('forward_primer', models.CharField(blank=True, max_length=64)),
                ('reverse_primer', models.CharField(blank=True, max_length=64)),
                ('max_ee', models.PositiveIntegerField(blank=True, default=2, null=True)),
                ('min_len', models.PositiveIntegerField(blank=True, default=50, null=True)),
                ('max_len', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.FileField(upload_to=olc_webportalv2.ampliseq.models.set_metadata_file_path)),
                ('dada_ref_taxonomy', models.CharField(choices=[('silva=132', 'Silva version 132'), ('silva=132', 'Silva version 138'), ('rdp=18', 'RDP version 18')], default='silva=132', max_length=50)),
                ('qiime_ref_taxonomy', models.CharField(blank=True, choices=[('silva=132', 'Silva version 132'), ('silva=132', 'Silva version 138'), ('rdp=18', 'RDP version 18')], max_length=50)),
                ('classifier', models.FileField(upload_to=olc_webportalv2.ampliseq.models.set_classifier_file_path)),
                ('exclude_taxa', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None)),
                ('trunc_len_f', models.PositiveIntegerField(blank=True, null=True)),
                ('trunc_len_r', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
