# Generated by Django 2.1.11 on 2023-07-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='dada_ref_taxonomy',
            field=models.CharField(choices=[('silva=132', 'Silva version 132'), ('silva=138', 'Silva version 138'), ('rdp=18', 'RDP version 18')], default='silva=132', max_length=50),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='qiime_ref_taxonomy',
            field=models.CharField(blank=True, choices=[('silva=132', 'Silva version 132'), ('silva=138', 'Silva version 138'), ('rdp=18', 'RDP version 18')], max_length=50),
        ),
    ]
