# Generated by Django 2.1.11 on 2023-07-06 15:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0002_auto_20230706_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='exclude_taxa',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='mitochondria,chloroplast', max_length=64), size=None),
        ),
    ]
