# Generated by Django 2.1.11 on 2023-07-07 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0003_auto_20230706_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='dada_ref_taxonomy',
            field=models.CharField(choices=[('silva=132', 'Silva version 132'), ('silva=138', 'Silva version 138'), ('rdp=18', 'RDP version 18')], default='silva=132', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='exclude_taxa',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='forward_primer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='max_ee',
            field=models.PositiveIntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='max_len',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='min_len',
            field=models.PositiveIntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='qiime_ref_taxonomy',
            field=models.CharField(choices=[('silva=132', 'Silva version 132'), ('silva=138', 'Silva version 138'), ('rdp=18', 'RDP version 18')], default='silva=132', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='reverse_primer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='trunc_len_f',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='trunc_len_r',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
