# Generated by Django 2.1.11 on 2023-07-07 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0004_auto_20230707_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='exclude_taxa',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='forward_primer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='max_ee',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='max_len',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='min_len',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='reverse_primer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='trunc_len_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='trunc_len_r',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
