# Generated by Django 2.1.11 on 2023-07-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0005_auto_20230707_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ampliseqrequest',
            name='container_name',
        ),
        migrations.AddField(
            model_name='containername',
            name='ampliseq_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampliseq_analysis', to='ampliseq.AmpliSeqRequest'),
        ),
    ]
