# Generated by Django 2.1.11 on 2023-07-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0006_auto_20230710_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containername',
            name='ampliseq_analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ampliseq_analysis', to='ampliseq.AmpliSeqRequest'),
        ),
    ]
