# Generated by Django 2.1.11 on 2023-07-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0007_auto_20230710_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containername',
            name='ampliseq_analysis',
        ),
        migrations.AddField(
            model_name='ampliseqrequest',
            name='container_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='ampliseq.ContainerName'),
        ),
    ]
