# Generated by Django 2.1.11 on 2023-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0008_auto_20230710_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='container_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
