# Generated by Django 2.1.11 on 2023-07-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0010_auto_20230711_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='container_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='ampliseq.ContainerName'),
        ),
    ]
