# Generated by Django 2.1.11 on 2023-07-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0011_auto_20230711_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='container_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
