# Generated by Django 2.1.11 on 2023-07-11 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0012_auto_20230711_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
