# Generated by Django 2.1.11 on 2023-07-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0013_auto_20230711_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ampliseqrequest',
            old_name='errors',
            new_name='error_list',
        ),
    ]
