# Generated by Django 2.1.11 on 2023-07-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0015_ampliseqrequest_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='taxonomy',
            field=models.CharField(choices=[('dada', 'Use pre-trained classifier for DADA2 taxonomic assignment'), ('qiime', 'Use pre-trained classifier for QIIME2 taxonomic assignment'), ('qiime_custom', 'Use custom classifier for QIIME2 taxonomic assignment')], max_length=50, null=True),
        ),
    ]
