# Generated by Django 2.1.11 on 2023-07-11 19:37

from django.db import migrations, models
import olc_webportalv2.ampliseq.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0017_auto_20230711_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='classifier',
            field=models.FileField(blank=True, null=True, upload_to=olc_webportalv2.ampliseq.models.set_classifier_file_path),
        ),
    ]
