# Generated by Django 2.1.11 on 2023-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0019_auto_20230712_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='container_name',
            field=models.CharField(max_length=64),
        ),
    ]
