# Generated by Django 2.1.11 on 2023-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0020_auto_20230712_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='container_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
