# Generated by Django 2.1.11 on 2023-07-12 15:47

from django.db import migrations, models
import olc_webportalv2.ampliseq.models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0021_auto_20230712_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='metadata',
            field=models.FileField(blank=True, null=True, upload_to=olc_webportalv2.ampliseq.models.set_metadata_file_path),
        ),
    ]
