# Generated by Django 2.1.11 on 2023-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0022_auto_20230712_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='classifier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='metadata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
