# Generated by Django 2.1.11 on 2023-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0023_auto_20230712_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='exclude_taxa',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
