# Generated by Django 2.1.11 on 2023-07-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0024_auto_20230712_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpliSeqAzureTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(max_length=256)),
                ('ampliseq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='ampliseq.AmpliSeqRequest')),
            ],
        ),
    ]
