# Generated by Django 2.1.11 on 2023-07-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0025_ampliseqazuretask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ampliseqrequest',
            old_name='report_download_link',
            new_name='execution_report_download_link',
        ),
        migrations.RenameField(
            model_name='ampliseqrequest',
            old_name='summary_download_link',
            new_name='execution_timeline_download_link',
        ),
        migrations.AddField(
            model_name='ampliseqrequest',
            name='execution_trace_download_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
