# Generated by Django 2.1.11 on 2023-07-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0026_auto_20230717_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampliseqrequest',
            name='upload',
            field=models.BooleanField(default=False),
        ),
    ]
