# Generated by Django 2.1.11 on 2023-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0027_ampliseqrequest_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='qiime_ref_taxonomy',
            field=models.CharField(choices=[('silva=138', 'Silva version 138'), ('rdp=18', 'RDP version 18')], default='silva=138', max_length=50, null=True),
        ),
    ]
