# Generated by Django 2.1.11 on 2024-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0029_ampliseqrequest_results_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='taxonomy',
            field=models.CharField(choices=[('dada', 'Train a classifier for DADA2 taxonomic assignment'), ('qiime', 'Train a classifier for QIIME2 taxonomic assignment'), ('qiime_custom', 'Use custom classifier for QIIME2 taxonomic assignment')], default='dada', max_length=50, null=True),
        ),
    ]
