# Generated by Django 2.1.11 on 2024-03-26 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampliseq', '0030_auto_20240205_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampliseqazuretask',
            name='exit_code_file',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='error_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='execution_report_download_link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='execution_timeline_download_link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='execution_trace_download_link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='exit_code_file',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='ampliseqrequest',
            name='results_download_link',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
