# Generated by Django 2.1.11 on 2020-02-04 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PrimerFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('analysistype', models.CharField(choices=[('custom', 'Custom EPCR'), ('vtyper', 'Verotoxin')], default='custom', max_length=50)),
                ('ampliconsize', models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1000)])),
                ('mismatches', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('export_amplicons', models.BooleanField(default=True)),
                ('primer_file', models.FileField(blank=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='primerazurerequest',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_azure_request', to='primer_finder.PrimerFinder'),
        ),
    ]
