# Generated by Django 2.1.11 on 2022-07-13 17:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primer_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusivityPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusivity_genus', models.CharField(choices=[('campylobacter', 'Campylobacter'), ('escherichia', 'Escherichia'), ('listeria', 'Listeria'), ('salmonella', 'Salmonella')], default='salmonella', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='ExclusivitySequences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusivity_seqid', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='InclusivityPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivity_genus', models.CharField(choices=[('campylobacter', 'Campylobacter'), ('escherichia', 'Escherichia'), ('listeria', 'Listeria'), ('salmonella', 'Salmonella')], default='escherichia', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='InclusivitySequences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivity_seqid', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='PrimerFinderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivity_seqids', models.CharField(blank=True, max_length=64)),
                ('exclusivity_seqids', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PrimerValidatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('report', models.TextField(blank=True)),
                ('min_amplicon_size', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('max_amplicon_size', models.IntegerField(default=1500, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('mismatches', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('contig_breaks', models.BooleanField(default=False)),
                ('range_buffer', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)])),
                ('primer_sequence', models.TextField()),
                ('inclusivity_panel', models.CharField(blank=True, max_length=64)),
                ('exclusivity_panel', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='primervalidatorproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrimerValidatorProject',
        ),
        migrations.AddField(
            model_name='inclusivitysequences',
            name='inclusivity_seqids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivity_sequences', to='primer_finder.PrimerFinderRequest'),
        ),
        migrations.AddField(
            model_name='inclusivitypanel',
            name='inclusivity_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivity_genera', to='primer_finder.PrimerValidatorRequest'),
        ),
        migrations.AddField(
            model_name='exclusivitysequences',
            name='exclusivity_seqids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusivity_sequences', to='primer_finder.PrimerFinderRequest'),
        ),
        migrations.AddField(
            model_name='exclusivitypanel',
            name='exclusivity_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusivity_genera', to='primer_finder.PrimerValidatorRequest'),
        ),
    ]
