# Generated by Django 2.1.11 on 2022-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0002_auto_20220713_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primervalidatorrequest',
            name='primer_sequence',
            field=models.TextField(blank=True),
        ),
    ]
