# Generated by Django 2.1.11 on 2022-07-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0003_auto_20220715_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusivityIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=64)),
                ('total_mismatch', models.IntegerField()),
                ('seqid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusivity_seqid_id', to='primer_finder.PrimerValidatorRequest')),
            ],
        ),
        migrations.CreateModel(
            name='InclusivityIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=64)),
                ('total_mismatch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrimerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_name', models.CharField(max_length=64)),
                ('primer_sequence', models.CharField(max_length=64)),
                ('primers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_id', to='primer_finder.PrimerValidatorRequest')),
            ],
        ),
        migrations.AlterField(
            model_name='inclusivitypanel',
            name='inclusivity_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivity_id', to='primer_finder.PrimerValidatorRequest'),
        ),
        migrations.AddField(
            model_name='inclusivityids',
            name='seqid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivity_seqid_id', to='primer_finder.InclusivityPanel'),
        ),
    ]
