# Generated by Django 2.1.11 on 2022-07-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0004_auto_20220718_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primervalidatorrequest',
            old_name='primer_sequence',
            new_name='primer_sequences',
        ),
    ]
