# Generated by Django 2.1.11 on 2022-07-18 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0005_auto_20220718_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primervalidatorrequest',
            name='exclusivity_panel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='primervalidatorrequest',
            name='inclusivity_panel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
    ]
