# Generated by Django 2.1.11 on 2022-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0006_auto_20220718_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivitypanel',
            name='exclusivity_genus',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='inclusivitypanel',
            name='inclusivity_genus',
            field=models.CharField(max_length=64),
        ),
    ]
