# Generated by Django 2.1.11 on 2022-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0008_auto_20220718_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivityids',
            name='total_mismatch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inclusivityids',
            name='total_mismatch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
