# Generated by Django 2.1.11 on 2022-07-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0009_auto_20220718_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inclusivityids',
            options={'verbose_name': 'inclusivity sequence details', 'verbose_name_plural': 'inclusivity sequence details'},
        ),
    ]
