# Generated by Django 2.1.11 on 2022-07-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0010_auto_20220718_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exclusivityids',
            options={'verbose_name': 'exclusivity sequence details', 'verbose_name_plural': 'exclusivity sequence details'},
        ),
    ]
