# Generated by Django 2.1.11 on 2022-07-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0011_auto_20220718_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivityids',
            name='seqid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusivity_seqid_id', to='primer_finder.ExclusivityPanel'),
        ),
        migrations.AlterField(
            model_name='exclusivityids',
            name='total_mismatch',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inclusivityids',
            name='total_mismatch',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
