# Generated by Django 2.1.11 on 2022-07-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0012_auto_20220718_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_header', models.CharField(max_length=64)),
                ('primer_sequence', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'primers',
                'verbose_name_plural': 'primers',
            },
        ),
        migrations.RemoveField(
            model_name='primerset',
            name='primer_sequence',
        ),
        migrations.AddField(
            model_name='primers',
            name='primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer', to='primer_finder.PrimerSet'),
        ),
    ]
