# Generated by Django 2.1.11 on 2022-07-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0013_auto_20220719_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusivityids',
            old_name='seqid_id',
            new_name='panel',
        ),
        migrations.RenameField(
            model_name='inclusivityids',
            old_name='seqid_id',
            new_name='panel',
        ),
    ]
