# Generated by Django 2.1.11 on 2022-07-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0014_auto_20220719_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusivitypanel',
            old_name='exclusivity_panel',
            new_name='validator_request',
        ),
        migrations.RenameField(
            model_name='inclusivitypanel',
            old_name='inclusivity_panel',
            new_name='validator_request',
        ),
        migrations.RenameField(
            model_name='primerset',
            old_name='primers',
            new_name='validator_request',
        ),
    ]
