# Generated by Django 2.1.11 on 2022-07-19 20:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0016_auto_20220719_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='primervalidatorrequest',
            name='emails_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='primervalidatorrequest',
            name='errors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='primervalidatorrequest',
            name='exit_code_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='validatorazurerequest',
            name='validator_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='primer_finder.PrimerValidatorRequest'),
        ),
    ]
