# Generated by Django 2.1.11 on 2022-07-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0017_auto_20220719_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=64)),
                ('panel', models.CharField(max_length=64)),
                ('validator_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_details', to='primer_finder.PrimerValidatorRequest')),
            ],
        ),
        migrations.CreateModel(
            name='SEQID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=64)),
                ('sequence_path', models.CharField(max_length=64)),
                ('amplicon_length', models.CharField(blank=True, default='', max_length=64)),
                ('contig', models.CharField(blank=True, default='', max_length=64)),
                ('direction', models.CharField(blank=True, default='', max_length=64)),
                ('forward_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('forward_mismatch_details', models.CharField(blank=True, default='', max_length=64)),
                ('forward_pos', models.CharField(blank=True, default='', max_length=64)),
                ('forward_query', models.CharField(blank=True, default='', max_length=64)),
                ('forward_ref', models.CharField(blank=True, default='', max_length=64)),
                ('primer_set', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_mismatch_details', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_pos', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_query', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_ref', models.CharField(blank=True, default='', max_length=64)),
                ('start_pos', models.CharField(blank=True, default='', max_length=64)),
                ('stop_pos', models.CharField(blank=True, default='', max_length=64)),
                ('total_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='primer_finder.Panel')),
            ],
            options={
                'verbose_name_plural': 'sequence details',
                'verbose_name': 'sequence details',
            },
        ),
        migrations.RemoveField(
            model_name='exclusivityids',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='exclusivitypanel',
            name='validator_request',
        ),
        migrations.RemoveField(
            model_name='inclusivityids',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='inclusivitypanel',
            name='validator_request',
        ),
        migrations.DeleteModel(
            name='ExclusivityIDs',
        ),
        migrations.DeleteModel(
            name='ExclusivityPanel',
        ),
        migrations.DeleteModel(
            name='InclusivityIDs',
        ),
        migrations.DeleteModel(
            name='InclusivityPanel',
        ),
    ]
