# Generated by Django 2.1.11 on 2022-07-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0018_auto_20220720_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqid',
            name='sequence',
            field=models.TextField(default=''),
        ),
    ]
