# Generated by Django 2.1.11 on 2022-07-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0019_seqid_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqid',
            name='primer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seqid_primer', to='primer_finder.Primers'),
        ),
    ]
