# Generated by Django 2.1.11 on 2022-07-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0020_seqid_primer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqid',
            name='primer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seqid_primer_set', to='primer_finder.PrimerSet'),
        ),
    ]
