# Generated by Django 2.1.11 on 2022-07-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0021_auto_20220727_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='primervalidatorrequest',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
