# Generated by Django 2.1.11 on 2022-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0022_primervalidatorrequest_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primervalidatorrequest',
            old_name='download_link',
            new_name='report_download_link',
        ),
        migrations.AddField(
            model_name='primervalidatorrequest',
            name='summary_download_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
