# Generated by Django 2.1.11 on 2022-08-04 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primer_finder', '0023_auto_20220728_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimerValidatorRequest',
            new_name='PrimerVerifierRequest',
        ),
        migrations.RenameModel(
            old_name='ValidatorAzureRequest',
            new_name='VerifierAzureRequest',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='validator_request',
            new_name='verifier_request',
        ),
        migrations.RenameField(
            model_name='primerset',
            old_name='validator_request',
            new_name='verifier_request',
        ),
        migrations.RenameField(
            model_name='verifierazurerequest',
            old_name='validator_request',
            new_name='verifier_request',
        ),
    ]
