# Generated by Django 2.1.11 on 2022-08-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0024_auto_20220804_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panel',
            new_name='VerifierPanel',
        ),
        migrations.RenameModel(
            old_name='Primers',
            new_name='VerifierPrimers',
        ),
        migrations.RenameModel(
            old_name='PrimerSet',
            new_name='VerifierPrimerSet',
        ),
        migrations.RenameModel(
            old_name='SEQID',
            new_name='VerifierSEQID',
        ),
    ]
