# Generated by Django 2.1.11 on 2022-08-08 19:55

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primer_finder', '0025_auto_20220808_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=64)),
                ('panel', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('report_download_link', models.CharField(blank=True, max_length=256)),
                ('summary_download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('errors', models.TextField(blank=True, default='')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
                ('emails_array', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('report', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('mismatches', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('forward_primer', models.TextField()),
                ('reverse_primer', models.TextField()),
                ('inclusivity_panel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('exclusivity_panel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorSEQID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=64)),
                ('sequence_path', models.CharField(max_length=64)),
                ('amplicon_length', models.CharField(blank=True, default='', max_length=64)),
                ('contig', models.CharField(blank=True, default='', max_length=64)),
                ('direction', models.CharField(blank=True, default='', max_length=64)),
                ('forward_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('forward_mismatch_details', models.CharField(blank=True, default='', max_length=64)),
                ('forward_pos', models.CharField(blank=True, default='', max_length=64)),
                ('forward_query', models.CharField(blank=True, default='', max_length=64)),
                ('forward_ref', models.CharField(blank=True, default='', max_length=64)),
                ('primer_set', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_mismatch_details', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_pos', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_query', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_ref', models.CharField(blank=True, default='', max_length=64)),
                ('sequence', models.TextField(default='')),
                ('start_pos', models.CharField(blank=True, default='', max_length=64)),
                ('stop_pos', models.CharField(blank=True, default='', max_length=64)),
                ('total_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='primer_finder.ValidatorPanel')),
            ],
            options={
                'verbose_name': 'sequence details',
                'verbose_name_plural': 'sequence details',
            },
        ),
        migrations.AddField(
            model_name='validatorpanel',
            name='verifier_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_details', to='primer_finder.ValidatorRequest'),
        ),
    ]
