# Generated by Django 2.1.11 on 2022-08-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0026_auto_20220808_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validatorpanel',
            old_name='verifier_request',
            new_name='validator_request',
        ),
    ]
