# Generated by Django 2.1.11 on 2022-08-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0027_auto_20220808_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorPrimers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_header', models.CharField(max_length=64)),
                ('primer_sequence', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'validator primers',
                'verbose_name_plural': 'validator primers',
            },
        ),
        migrations.CreateModel(
            name='ValidatorPrimerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_name', models.CharField(max_length=64)),
                ('validator_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_id', to='primer_finder.ValidatorRequest')),
            ],
        ),
        migrations.AlterModelOptions(
            name='validatorseqid',
            options={'verbose_name': 'validator sequence details', 'verbose_name_plural': 'validator sequence details'},
        ),
        migrations.AlterModelOptions(
            name='verifierprimers',
            options={'verbose_name': 'verifier primers', 'verbose_name_plural': 'verifier primers'},
        ),
        migrations.AlterModelOptions(
            name='verifierseqid',
            options={'verbose_name': 'verifier sequence details', 'verbose_name_plural': 'verifier sequence details'},
        ),
        migrations.AddField(
            model_name='validatorprimers',
            name='primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer', to='primer_finder.ValidatorPrimerSet'),
        ),
        migrations.AddField(
            model_name='validatorseqid',
            name='primer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seqid_primer_set', to='primer_finder.ValidatorPrimerSet'),
        ),
    ]
