# Generated by Django 2.1.11 on 2022-08-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0028_auto_20220809_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerValidatorAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
                ('validator_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='primer_finder.ValidatorRequest')),
            ],
        ),
    ]
