# Generated by Django 2.1.11 on 2022-08-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0029_primervalidatorazurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorrequest',
            name='totals',
            field=models.TextField(blank=True),
        ),
    ]
