# Generated by Django 2.1.11 on 2022-10-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0030_validatorrequest_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorrequest',
            name='probe_sequence',
            field=models.TextField(blank=True),
        ),
    ]
