# Generated by Django 2.1.11 on 2025-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0031_validatorrequest_probe_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerverifierrequest',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Processing', 'Processing'), ('Complete', 'Complete'), ('Error', 'Error')], db_index=True, default='Unprocessed', max_length=64),
        ),
    ]
