# Generated by Django 2.1.11 on 2025-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0032_auto_20250221_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerverifierrequest',
            name='probe_sequence',
            field=models.TextField(blank=True),
        ),
    ]
