# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-04 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geneseekr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneseekrrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geneseekrdetail',
            name='geneseekr_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geneseekrdetail', to='geneseekr.GeneSeekrRequest'),
        ),
        migrations.AddField(
            model_name='azuregeneseekrtask',
            name='geneseekr_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='geneseekr.GeneSeekrRequest'),
        ),
    ]
