# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0002_auto_20180904_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBlastHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contig_name', models.CharField(max_length=128)),
                ('query_coverage', models.FloatField()),
                ('percent_identity', models.FloatField()),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('e_value', models.FloatField()),
                ('geneseekr_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topblasthits', to='geneseekr.GeneSeekrRequest')),
            ],
            options={
                'ordering': ['e_value', '-percent_identity', '-query_coverage'],
            },
        ),
    ]
