# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0003_topblasthit'),
    ]

    operations = [
        migrations.AddField(
            model_name='topblasthit',
            name='gene_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
