# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-21 14:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0004_topblasthit_gene_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneseekrrequest',
            name='gene_targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='topblasthit',
            name='query_end_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topblasthit',
            name='query_start_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
