# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-26 19:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geneseekr', '0006_topblasthit_query_sequence_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsnpAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ParsnpTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=[], size=None)),
                ('newick_tree', models.CharField(blank=True, max_length=10000)),
                ('download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parsnpazurerequest',
            name='tree_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='geneseekr.ParsnpTree'),
        ),
    ]
