# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0007_auto_20181126_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneseekrrequest',
            name='download_link_sequence',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
