# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-21 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0008_geneseekrrequest_download_link_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneseekrrequest',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
