# Generated by Django 2.1.5 on 2019-02-18 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0011_geneseekrrequest_emails_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneseekrrequest',
            name='emails_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=[], null=True, size=None),
        ),
    ]
