# Generated by Django 2.1.5 on 2019-02-19 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0012_auto_20190218_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsnptree',
            name='emails_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=[], null=True, size=None),
        ),
    ]
