# Generated by Django 2.1.5 on 2019-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0013_parsnptree_emails_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsnptree',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
