# Generated by Django 2.1.5 on 2019-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0015_auto_20190401_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsnptree',
            name='tree_program',
            field=models.CharField(default='parsnp', max_length=10000),
        ),
    ]
