# Generated by Django 2.1.5 on 2019-04-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0016_auto_20190401_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsnptree',
            name='number_diversitree_strains',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
