# Generated by Django 2.1.5 on 2019-04-08 14:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geneseekr', '0021_remove_amrsummary_amr_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProkkaAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProkkaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=[], size=None)),
                ('download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('emails_array', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=[], null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='amrazurerequest',
            name='exit_code_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='prokkaazurerequest',
            name='prokka_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='geneseekr.ProkkaRequest'),
        ),
    ]
