# Generated by Django 2.1.5 on 2019-04-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0022_auto_20190408_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsnpazurerequest',
            old_name='tree_request',
            new_name='parsnp_request',
        ),
    ]
