# Generated by Django 2.1.5 on 2019-04-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geneseekr', '0023_auto_20190408_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearestNeighbors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('number_neighbors', models.IntegerField()),
                ('download_link', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NearNeighborDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=24)),
                ('distance', models.FloatField()),
                ('near_neighbor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_detail', to='geneseekr.NearestNeighbors')),
            ],
        ),
    ]
