# Generated by Django 2.1.5 on 2019-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0024_nearestneighbors_nearneighbordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearestneighbors',
            name='status',
            field=models.CharField(blank=True, default='Unprocessed', max_length=64, null=True),
        ),
    ]
