# Generated by Django 2.1.5 on 2019-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0025_nearestneighbors_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearestneighbors',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
