# Generated by Django 2.1.5 on 2019-08-23 19:32

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0030_auto_20190726_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amrdetail',
            name='amr_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='geneseekrdetail',
            name='geneseekr_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='geneseekrrequest',
            name='geneseekr_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='prokkarequest',
            name='emails_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='prokkarequest',
            name='other_input_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=64), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='prokkarequest',
            name='seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, null=True, size=None),
        ),
    ]
