# Generated by Django 2.1.5 on 2019-10-18 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0032_auto_20190823_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azuregeneseekrtask',
            name='geneseekr_request',
        ),
        migrations.AddField(
            model_name='nearestneighbors',
            name='emails_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='AzureGeneSeekrTask',
        ),
    ]
