# Generated by Django 2.1.5 on 2019-10-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0033_auto_20191018_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsnptree',
            name='tree_program',
        ),
    ]
