# Generated by Django 2.1.5 on 2019-10-22 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geneseekr', '0034_remove_parsnptree_tree_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParsnpTree',
            new_name='Tree',
        ),
    ]
