# Generated by Django 2.1.5 on 2019-10-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0035_auto_20191022_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParsnpAzureRequest',
            new_name='TreeAzureRequest',
        ),
    ]
