# Generated by Django 2.1.11 on 2022-07-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0037_auto_20191022_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSeekrAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
                ('geneseekr_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='geneseekr.GeneSeekrRequest')),
            ],
        ),
    ]
