# Generated by Django 2.1.11 on 2022-07-05 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0038_geneseekrazurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneseekrrequest',
            name='other_input_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=64), null=True, size=None),
        ),
    ]
