# Generated by Django 2.1.11 on 2022-07-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0039_geneseekrrequest_other_input_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneseekrrequest',
            name='error',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
