# Generated by Django 2.1.11 on 2022-07-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0040_geneseekrrequest_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneseekrrequest',
            name='error',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
