# Generated by Django 2.1.11 on 2024-01-17 16:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0042_geneseekrrequest_benchmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneseekrrequest',
            name='seqids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
    ]
