# Generated by Django 2.1.11 on 2024-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0043_auto_20240117_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneseekrdetail',
            name='seqid',
            field=models.CharField(default='', max_length=64),
        ),
    ]
