# Generated by Django 2.1.11 on 2024-06-12 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneseekr', '0044_auto_20240117_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneseekrrequest',
            name='other_input_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, null=True, size=None),
        ),
    ]
