# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-04 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_multisample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmulti',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genomeqamlresult',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomeqaml_result', to='new_multisample.Sample'),
        ),
        migrations.AddField(
            model_name='genesipprresultssixteens',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixteens_results', to='new_multisample.Sample'),
        ),
        migrations.AddField(
            model_name='genesipprresultsserosippr',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_multisample.Sample'),
        ),
        migrations.AddField(
            model_name='genesipprresultsgdcs',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdcs_results', to='new_multisample.Sample'),
        ),
        migrations.AddField(
            model_name='genesipprresults',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genesippr_results', to='new_multisample.Sample'),
        ),
        migrations.AddField(
            model_name='confindrresults',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confindr_results', to='new_multisample.Sample'),
        ),
        migrations.AddField(
            model_name='amrresult',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amr_results', to='new_multisample.Sample'),
        ),
    ]
