# Generated by Django 2.1.11 on 2023-10-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'permissions': [('add', 'Can add containers')],
            },
        ),
        migrations.AddField(
            model_name='blobs',
            name='container_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='filezone.ContainerName'),
        ),
    ]
