# Generated by Django 2.1.11 on 2023-10-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0002_containername_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containername',
            name='user',
        ),
    ]
