# Generated by Django 2.1.11 on 2023-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0003_remove_containername_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containername',
            name='container_name',
            field=models.CharField(max_length=64),
        ),
    ]
