# Generated by Django 2.1.11 on 2023-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0004_auto_20231026_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobs',
            name='blob_name',
            field=models.CharField(max_length=1024),
        ),
    ]
