# Generated by Django 2.1.11 on 2023-10-27 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0005_auto_20231026_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobs',
            name='blob_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blobs',
            name='blob_size',
            field=models.CharField(default='0 B', max_length=64),
            preserve_default=False,
        ),
    ]
