# Generated by Django 2.1.11 on 2023-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0006_auto_20231027_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobs',
            name='blob_download_link',
            field=models.CharField(default=5, max_length=128),
            preserve_default=False,
        ),
    ]
