# Generated by Django 2.1.11 on 2023-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0007_blobs_blob_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobs',
            name='blob_download_link',
            field=models.CharField(max_length=256),
        ),
    ]
