# Generated by Django 2.1.11 on 2023-11-20 19:45

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0008_auto_20231101_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_matches', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('file_regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_regex', to='filezone.ContainerName')),
            ],
        ),
        migrations.CreateModel(
            name='Regexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_regex', models.CharField(default='*', max_length=64)),
                ('file_regex', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
