# Generated by Django 2.1.11 on 2023-11-20 20:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0009_files_regexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regexes',
            name='container_regex',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, null=True, size=None),
        ),
    ]
