# Generated by Django 2.1.11 on 2023-11-20 20:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0010_auto_20231120_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexes',
            name='container_regex_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='regexes',
            name='file_regex_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='regexes',
            name='container_regex',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='regexes',
            name='file_regex',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
