# Generated by Django 2.1.11 on 2023-11-21 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0011_auto_20231120_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regexes',
            name='container_regex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regexes',
            name='container_regex_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='regexes',
            name='file_regex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regexes',
            name='file_regex_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
