# Generated by Django 2.1.11 on 2023-11-21 20:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0012_auto_20231121_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_regex',
        ),
        migrations.AddField(
            model_name='regexes',
            name='file_matches',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
