# Generated by Django 2.1.11 on 2023-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0013_auto_20231121_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexes',
            name='status',
            field=models.CharField(default='Unprocessed', max_length=64),
        ),
    ]
