# Generated by Django 2.1.11 on 2023-11-22 19:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0014_regexes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexes',
            name='file_ajax',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
