# Generated by Django 2.1.11 on 2023-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0015_regexes_file_ajax'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexes',
            name='container_exclude_regex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regexes',
            name='file_exclude_regex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
