# Generated by Django 2.1.11 on 2023-11-28 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0016_auto_20231127_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexes',
            name='container_exclude_regex_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='regexes',
            name='file_exclude_regex_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
