# Generated by Django 2.1.11 on 2023-12-11 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filezone', '0017_auto_20231128_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexes',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2023, 12, 11)),
            preserve_default=False,
        ),
    ]
