# Generated by Django 2.1.11 on 2022-08-08 17:47

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primer_finder', '0025_auto_20220808_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerValidatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('report_download_link', models.CharField(blank=True, max_length=256)),
                ('summary_download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('errors', models.TextField(blank=True, default='')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
                ('emails_array', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('report', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('mismatches', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('forward_primer', models.TextField(blank=True)),
                ('reverse_primer', models.TextField(blank=True)),
                ('inclusivity_panel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('exclusivity_panel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
