# Generated by Django 2.1.11 on 2022-08-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0026_primervalidatorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=64)),
                ('panel', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorSEQID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.CharField(max_length=64)),
                ('sequence_path', models.CharField(max_length=64)),
                ('amplicon_length', models.CharField(blank=True, default='', max_length=64)),
                ('contig', models.CharField(blank=True, default='', max_length=64)),
                ('direction', models.CharField(blank=True, default='', max_length=64)),
                ('forward_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('forward_mismatch_details', models.CharField(blank=True, default='', max_length=64)),
                ('forward_pos', models.CharField(blank=True, default='', max_length=64)),
                ('forward_query', models.CharField(blank=True, default='', max_length=64)),
                ('forward_ref', models.CharField(blank=True, default='', max_length=64)),
                ('primer_set', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_mismatch_details', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_pos', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_query', models.CharField(blank=True, default='', max_length=64)),
                ('reverse_ref', models.CharField(blank=True, default='', max_length=64)),
                ('sequence', models.TextField(default='')),
                ('start_pos', models.CharField(blank=True, default='', max_length=64)),
                ('stop_pos', models.CharField(blank=True, default='', max_length=64)),
                ('total_mismatch', models.CharField(blank=True, default='', max_length=64)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='primer_finder.ValidatorPanel')),
            ],
            options={
                'verbose_name': 'sequence details',
                'verbose_name_plural': 'sequence details',
            },
        ),
        migrations.AlterField(
            model_name='primervalidatorrequest',
            name='forward_primer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='primervalidatorrequest',
            name='reverse_primer',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='validatorpanel',
            name='verifier_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_details', to='primer_finder.PrimerValidatorRequest'),
        ),
    ]
