# Generated by Django 2.1.11 on 2022-08-08 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primer_finder', '0027_auto_20220808_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimerValidatorRequest',
            new_name='ValidatorRequest',
        ),
    ]
