# Generated by Django 2.1.11 on 2022-08-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_finder', '0029_validatorazurerequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidatorAzureRequest',
            new_name='PrimerValidatorAzureRequest',
        ),
    ]
