# Generated by Django 2.1.11 on 2020-03-12 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirTyperAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VirTyperFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_file', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VirTyperProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('report', models.CharField(blank=True, max_length=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VirTyperRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_ID', models.CharField(choices=[('STH', 'St. Hyacinthe'), ('BUR', 'Burnaby')], default='STH', max_length=64)),
                ('isolate_source', models.CharField(max_length=64)),
                ('LSTS_ID', models.CharField(max_length=64)),
                ('putative_classification', models.CharField(choices=[('NOVI', 'Norovirus genogroup 1'), ('NOVII', 'Norovirus genogroup 2'), ('HAV', 'Hepatitus A'), ('MNV', 'Murine norovirus')], default='NOVI', max_length=50)),
                ('sample_name', models.CharField(max_length=64)),
                ('subunit', models.PositiveIntegerField(blank=True, null=True)),
                ('date_received', models.DateField()),
                ('analyst_name', models.CharField(max_length=64)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_request', to='vir_typer.VirTyperProject')),
            ],
        ),
        migrations.CreateModel(
            name='VirTyperResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(max_length=50)),
                ('orientation', models.CharField(max_length=50)),
                ('forward_primer', models.CharField(max_length=50)),
                ('reverse_primer', models.CharField(max_length=50)),
                ('trimmed_sequence', models.CharField(max_length=256)),
                ('trimmed_sequence_len', models.CharField(max_length=50)),
                ('trimmed_quality_max', models.CharField(max_length=50)),
                ('trimmed_quality_mean', models.CharField(max_length=50)),
                ('trimmed_quality_min', models.CharField(max_length=50)),
                ('trimmed_quality_stdev', models.CharField(max_length=50)),
                ('sequence_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_results', to='vir_typer.VirTyperFiles')),
            ],
        ),
        migrations.AddField(
            model_name='virtyperfiles',
            name='sample_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='vir_typer.VirTyperRequest'),
        ),
        migrations.AddField(
            model_name='virtyperazurerequest',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_azure_request', to='vir_typer.VirTyperProject'),
        ),
        migrations.AlterUniqueTogether(
            name='virtyperrequest',
            unique_together={('sample_name', 'project_name'), ('LSTS_ID', 'project_name')},
        ),
        migrations.AlterUniqueTogether(
            name='virtyperproject',
            unique_together={('user', 'project_name')},
        ),
    ]
