# Generated by Django 2.1.5 on 2019-07-26 14:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirTyperAzureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code_file', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirTyperRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_link', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Unprocessed', max_length=64)),
                ('sample_name', models.CharField(max_length=50)),
                ('date_received', models.DateTimeField()),
                ('emails_array', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=[], null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='VirTyperSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='virtyperrequest',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vir_typer_sample', to='vir_typer.VirTyperSample'),
        ),
        migrations.AddField(
            model_name='virtyperrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtyperazurerequest',
            name='vir_typer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azuretask', to='vir_typer.VirTyperRequest'),
        ),
    ]
