# Generated by Django 2.1.5 on 2019-07-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VirTyperSample',
            new_name='VirTyperProject',
        ),
    ]
