# Generated by Django 2.1.5 on 2019-07-29 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0003_auto_20190729_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperfiles',
            name='sequence_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None),
        ),
    ]
