# Generated by Django 2.1.5 on 2019-07-29 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0004_auto_20190729_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirTyperBlobContainerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=64)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_blob_container', to='vir_typer.VirTyperProject')),
            ],
        ),
        migrations.AlterField(
            model_name='virtyperfiles',
            name='sample_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='vir_typer.VirTyperRequest'),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_request', to='vir_typer.VirTyperProject'),
        ),
    ]
