# Generated by Django 2.1.5 on 2019-07-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0005_auto_20190729_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtyperazurerequest',
            name='vir_typer_request',
        ),
        migrations.AddField(
            model_name='virtyperazurerequest',
            name='project_name',
            field=models.ForeignKey(default=76, on_delete=django.db.models.deletion.CASCADE, related_name='project_azure_request', to='vir_typer.VirTyperProject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtyperazurerequest',
            name='exit_code_file',
            field=models.CharField(default='NA', max_length=256),
            preserve_default=False,
        ),
    ]
