# Generated by Django 2.1.5 on 2019-07-30 12:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vir_typer', '0006_auto_20190730_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtyperrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='virtyperrequest',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='virtyperrequest',
            name='emails_array',
        ),
        migrations.RemoveField(
            model_name='virtyperrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='virtyperrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='virtyperproject',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtyperproject',
            name='download_link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='virtyperproject',
            name='emails_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=100), blank=True, default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='virtyperproject',
            name='status',
            field=models.CharField(default='Unprocessed', max_length=64),
        ),
        migrations.AddField(
            model_name='virtyperproject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
