# Generated by Django 2.1.5 on 2019-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0010_auto_20190802_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperproject',
            name='project_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
