# Generated by Django 2.1.5 on 2019-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0011_auto_20190802_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperproject',
            name='project_name',
            field=models.CharField(error_messages={'unique': 'Project name must be unique!'}, max_length=256, unique=True),
        ),
    ]
