# Generated by Django 2.1.5 on 2019-08-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0012_auto_20190802_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtyperrequest',
            name='analyst_name',
            field=models.CharField(default='ND', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtyperrequest',
            name='isolate_source',
            field=models.CharField(default='ND', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtyperrequest',
            name='lab_id',
            field=models.CharField(choices=[('STH', 'Ste-Hyacinthe'), ('BUR', 'Burnaby')], default='STH', max_length=20),
        ),
        migrations.AddField(
            model_name='virtyperrequest',
            name='lsts_id',
            field=models.CharField(default='ND', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtyperrequest',
            name='putative_classification',
            field=models.CharField(choices=[('NOV1', 'Norovirus genogroup 1'), ('NOV-', 'Norovirus genogroup 2'), ('HAV', 'Hepatitus A')], default='NOV1', max_length=50),
        ),
    ]
