# Generated by Django 2.1.5 on 2019-08-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0013_auto_20190802_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtyperrequest',
            name='subunit',
            field=models.CharField(default='ND', max_length=3),
            preserve_default=False,
        ),
    ]
