# Generated by Django 2.1.5 on 2019-08-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0014_virtyperrequest_subunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtyperrequest',
            old_name='lsts_id',
            new_name='LSTS_ID',
        ),
        migrations.RenameField(
            model_name='virtyperrequest',
            old_name='lab_id',
            new_name='lab_ID',
        ),
    ]
