# Generated by Django 2.1.5 on 2019-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0016_virtyperrequest_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtyperrequest',
            name='report',
        ),
        migrations.AddField(
            model_name='virtyperproject',
            name='report',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
