# Generated by Django 2.1.5 on 2019-08-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0017_auto_20190809_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperfiles',
            name='sequence_files',
            field=models.CharField(max_length=256),
        ),
    ]
