# Generated by Django 2.1.5 on 2019-08-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0018_auto_20190809_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtyperfiles',
            old_name='sequence_files',
            new_name='sequence_file',
        ),
    ]
