# Generated by Django 2.1.5 on 2019-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0021_auto_20190809_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtyperresults',
            name='trimmed_sequence_len',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtyperresults',
            name='trimmed_sequence',
            field=models.CharField(max_length=256),
        ),
    ]
