# Generated by Django 2.1.5 on 2019-08-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0022_auto_20190812_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperrequest',
            name='putative_classification',
            field=models.CharField(choices=[('NOVI', 'Norovirus genogroup 1'), ('NOVII', 'Norovirus genogroup 2'), ('HAV', 'Hepatitus A')], default='NOVI', max_length=50),
        ),
    ]
