# Generated by Django 2.1.5 on 2019-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0023_auto_20190820_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperproject',
            name='project_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='subunit',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
