# Generated by Django 2.1.5 on 2019-08-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0024_auto_20190820_1918'),
        ('vir_typer', '0023_auto_20190820_1823'),
    ]

    operations = [
    ]
