# Generated by Django 2.1.5 on 2019-08-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0025_merge_20190821_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperrequest',
            name='subunit',
            field=models.PositiveIntegerField(blank=True, max_length=3, null=True),
        ),
    ]
