# Generated by Django 2.1.5 on 2019-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0026_auto_20190821_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperrequest',
            name='lab_ID',
            field=models.CharField(choices=[('STH', 'St. Hyacinthe'), ('BUR', 'Burnaby')], default='STH', max_length=20),
        ),
    ]
