# Generated by Django 2.1.5 on 2019-08-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0027_auto_20190823_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperrequest',
            name='subunit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
