# Generated by Django 2.1.11 on 2019-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0028_auto_20190823_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperrequest',
            name='putative_classification',
            field=models.CharField(choices=[('NOVI', 'Norovirus genogroup 1'), ('NOVII', 'Norovirus genogroup 2'), ('HAV', 'Hepatitus A'), ('MNV', 'Murine norovirus')], default='NOVI', max_length=50),
        ),
    ]
