# Generated by Django 2.1.11 on 2019-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0029_auto_20191107_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When Created'),
        ),
    ]
