# Generated by Django 2.1.11 on 2019-11-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0032_auto_20191107_1834'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='virtyperrequest',
            unique_together={('sample_name', 'project_name')},
        ),
    ]
