# Generated by Django 2.1.11 on 2019-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0033_auto_20191107_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperrequest',
            name='sample_name',
            field=models.CharField(max_length=50),
        ),
    ]
