# Generated by Django 2.1.11 on 2019-11-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vir_typer', '0034_auto_20191107_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='virtyperrequest',
            unique_together={('sample_name', 'project_name'), ('LSTS_ID', 'project_name')},
        ),
    ]
