# Generated by Django 2.1.11 on 2019-11-20 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vir_typer', '0035_auto_20191108_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtyperproject',
            name='project_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='LSTS_ID',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='analyst_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='isolate_source',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='lab_ID',
            field=models.CharField(choices=[('STH', 'St. Hyacinthe'), ('BUR', 'Burnaby')], default='STH', max_length=64),
        ),
        migrations.AlterField(
            model_name='virtyperrequest',
            name='sample_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='virtyperproject',
            unique_together={('user', 'project_name')},
        ),
    ]
